version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ratings
      - DB_SSLMODE=disable
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - PORT=8000
      - GIN_MODE=release
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - api_logs:/app/logs

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ratings
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - API_URL=/docs/swagger.yaml
    volumes:
      - ./docs:/usr/share/nginx/html/docs
    depends_on:
      - api

volumes:
  postgres_data:
  api_logs: